liesel/goose/builder.py
liesel/goose/epoch.py
liesel/goose/warmup.py
tests/goose/test_engine.py
tests/goose/test_epoch.py
tests/goose/test_warmup.py

Allows thinning in warm-up epochs. Kernels that request the history, will get a thinned history.

allows thinning in non-posterior epochs

---

liesel/goose/summary_viz.py

In #3, I overlooked a necessary change in a helper function that controls the number of columns in multi-faceted trace, density, and correlation plots. The number of columns was previously determined by determining the number of unique entries in the "param" column of the helper data frame. Since this information is now located in the "param_label" column, the lookup had to be updated.

Fix layout of multi-faceted plots

---

conftest.py
liesel/__init__.py
liesel/logging.py
tests/liesel/test_distreg.py

This PR fixes the questionable behavior of changing the root logger's settings.
It also adds the current logger's name to the output of Liesel's log messages. This will allow users to identify the exact logger that is responsible for individual messages, such that those exact loggers can be edited more easily.

Fix logging

---

liesel/goose/summary_m.py
tests/goose/test_summary_object.py

Actually, the ordering of the indices seems to have been correct already. There was a small bug in `Summary.to_dataframe()`.
I did this:
1. Fixed the bug. For this, I had to add `Summary.per_chain` as an instance attribute, because the code in `to_dataframe()` has to work slightly differently depending on whether per_chain is True or False.
2. Added a test checking the bug fix (`test_per_chain_quantiles`)
3. Added a test checking that the indices are in the correct order (`test_quantity_shape`)
4. Added a documentation skeleton for `Summary.quantities`.
This test code...
```python
def test_per_chain_quantiles(result: SamplingResults):
summary = Summary(result, per_chain=True)
cols = [
"var_fqn",
"chain_index",
"mean",
"q_0.05",
"q_0.5",
"q_0.95",
"hdi_low",
"hdi_high",
]
df = …
```

fix quantile-summaries per chain

---

docs/source/conf.py

See [the Sphinx docs](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_ignore_module_a) and sphinx-doc/sphinx#9831. Please review, @jobrachem! :eyes:

Make Sphinx respect the module __all__ attribute

---

.pre-commit-config.yaml
conftest.py
liesel/experimental/pymc.py
liesel/goose/chain.py
liesel/goose/engine.py
liesel/goose/epoch.py
liesel/goose/gibbs.py
liesel/goose/hmc.py
liesel/goose/iwls.py
liesel/goose/kernel.py
liesel/goose/kernel_sequence.py
liesel/goose/mh_kernel.py
liesel/goose/models.py
liesel/goose/nuts.py
liesel/goose/rw.py
liesel/goose/types.py
liesel/liesel/goose.py
liesel/liesel/model.py
liesel/liesel/nodes.py
liesel/option.py
pyproject.toml
tests/goose/deterministic_kernels.py
tests/goose/kernels/model_lm.py
tests/goose/test_summary_object.py

the main change -- and the reason why so many files have been modified -- is that the new version of `isort` replaces a lot of imports from `typing` with imports from `collections.abc` (see https://github.com/asottile/pyupgrade/issues/558). Importing from `typing` is supposedly deprecated since 3.9.

Update versions of pre-commit-hooks

---

liesel/model/model.py
tests/model/test_graph_builder.py
tests/model/test_model.py

With these improved uniqueness checks, (1) it is now possible to add the same group twice to a graph builder, and (2) the group names are now checked for uniqueness when added directly to a model without a graph builder.
Do you see any problems, @jobrachem? :eyes:

Improve uniqueness checks for group names

---

liesel/distributions/mvn_degen.py
tests/distributions/test_mvn_degen.py

Closes #34.
The main function is `MultivariateNormalDegenerate._sample_n`, which allows us to sample like this:
```python
import jax.random as jrd
import jax.numpy as jnp
import liesel.model as lsl
key = jrd.PRNGKey(42)
D = jnp.diff(jnp.eye(5))
mvnd = lsl.MultivariateNormalDegenerate.from_penalty(loc=0.0, var=1.0, pen=D.T @ D)
mvnd.sample(seed=key)
```
Some notes:
1. I took the opportunity to also refactor the module a bit. I separated the helper function `_rank_and_log_pdet` into `_rank` and `_log_pdet`. Those new functions now take an array of eigenvalues instead of the precision matrix as input. 
2. The original function `_rank_and_log_pdet` had some special behavior to ensure efficiency, i.e., if you supplied both a `rank` and a `log_pdet` argument, the function essentially did …

Sample from mvn degenerate distribution

---

.github/workflows/doctest.yml
conftest.py
docs/source/conf.py

Adds a doctest action to our GitHub CI.
I could also imagine that this can simply be executed as an additional step in the existing `pytest-pull.yml` action. However, if it is its own action, we have a clearly defined distinction between failing doctests and failing unit tests, which I think is nice.

Add doctest action

---

liesel/model/nodes.py

This PR improves the docstrings for the Node and the Var, trying to clarify when it makes sense to declare a Var and when not. It also extends the docstrings of Obs and Param.
@jobrachem, please take a look and let me know if there's anything else you would like to see in the docstrings.

Improve docstrings for Node and Var, closes #43

---

docs/source/conf.py
setup.cfg

Apparently, the latest `pydata-sphinx-theme` [release](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.13.2) broke our usage of `sphinx-book-theme`.
This PR is a hotfix for this issue, it pins down the version. In the near future, a permanent fix will be merged in pydata-sphinx-theme: 
- https://github.com/pydata/pydata-sphinx-theme/issues/1274
- https://github.com/executablebooks/sphinx-book-theme/issues/711

Pin pydata-sphinx-theme version to fix docs

---

docs/source/index.rst
docs/source/tutorials/qmd/07-groups.qmd
docs/source/tutorials_overview.rst

Closes https://github.com/liesel-devs/liesel/issues/46
Builds on https://github.com/liesel-devs/liesel/pull/62, so that should be reviewed and merged first.
Here's a preview:

Add groups tutorial

---

liesel/model/distreg.py
liesel/model/nodes.py
tests/model/test_distreg.py

This PR includes only the mildest changes that I have in mind. For the other ones, I think it is more productive to open a separate PR and discuss those changes separately.
1. The mandatory order in which methods have to be called is reversed now (add_response -> add_predictor -> add_smooth). Closes https://github.com/liesel-devs/liesel-internal/issues/212
2. All model-building methods of the distregbuilder now return `self`, such that method-chaining is completely allowed. Closes https://github.com/liesel-devs/liesel-internal/issues/142
In [#212](https://github.com/liesel-devs/liesel-internal/issues/212), we talked about exchanging `add_prediction` for a mandatory argument in `add_response`. When working on the builder though, I felt like this would make usage more clunky than before, …

Refactor distregbuilder

---

liesel/model/model.py
tests/model/test_model.py

Implements a slightly improved version of the function in #37 as a method of the model class. Includes docstrings and tests.

Implement Model.simulate()

---

liesel/model/nodes.py
tests/model/test_node.py

If an error occurs in a call to `Calc.update()`, the exception is now re-raised with a printout of the instance repr.
See #78

Address #78

---

liesel/goose/hmc.py
liesel/goose/nuts.py
setup.cfg

Adapts the code for the hmc and nuts kernels to reflect changes in blackjax 1.0.0.
BlackJax changed their kernel interface. They use now classes with the member function `step`. I adapted the code such that it requires minimal changes in our code base. However, the readability is decreased and we should tidy it up either in this PR or in a subsequent PR.

Adapt to blackjax 1.0.0

---

docs/source/tutorials/qmd/04-mcycle.qmd
docs/source/tutorials/qmd/07-groups.qmd

Splitting up the single NUTS kernel into separate kernels for each parameter block resolved the problem.

Fix comparing samplers tutorial (closes #107)

---

CHANGELOG.md
liesel/goose/__init__.py

The class `liesel.goose.engine.SamplingResults` was not being exported, which annoyed me whenever I wanted to load results from a pickled file via `SamplingResults.pkl_load()`.
It is now exported via `liesel.goose`, which means it can be used as `gs.SamplingResults`.

Expose sampling results

---

.github/workflows/docs.yml
docs/source/goose.rst
docs/source/index.rst
docs/source/model.rst
docs/source/welcome.md
liesel/model/model.py
liesel/model/nodes.py

Adds two overview pages that provide a focused selection of the most important and most frequently used functionality in liesel.model and liesel.goose, respectively.
For review, I am afraid the docs should be built and inspected locally.
This PR is built on top of 
- #143 
I think #143 should be reviewed first.

Add model and goose overview

---

liesel/goose/builder.py
tests/goose/test_builder.py

Simple proposal to allow `seed` argument to be a key generated from `jax.random.PRNGKey` in the initialization of class `EngineBuilder`. Unfortunately type testing for the key is not really strict with `jax.Array`. However using `jnp.issubdtype(seed.dtype, jnp.uint32)` makes it more complicated. Stricter type testing seems only possible with `jax.random.key` currently, see [#16716](https://github.com/google/jax/issues/16716) and [#16781](https://github.com/google/jax/pull/16781) for current development on this.

Allow passing key as seed

---

docs/source/tutorials/qmd/07-groups.qmd

Add format string to the name of `basis_matrix`, to allow for the unique definition of several B-spline basis matrices.

fix name `basis_matrix` in 07-groups.qmd

---

.pre-commit-config.yaml
liesel/goose/engine.py
liesel/goose/kernel_sequence.py
liesel/model/goose.py
liesel/model/viz.py
tests/distributions/test_mvn_degen.py
tests/goose/test_builder.py

This PR simply adds the line `args: [--preview]` to the black configuration for our pre-commit. I think this is nice predominantly because this includes automatic formatting of long strings, which can be quite annoying. But there's another nice stuff, too, see here: https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html For example, dictionary and list formatting was also improved.

Use black preview in pre-commit

---

CHANGELOG.md
liesel/logging.py

Small update to make the liesel default logger behave more like you would expect.
- Increased the level of the `"liesel"` logger from `DEBUG` to `INFO`
- Removed the level `INFO` from the default handler for the liesel logger.
Now, you can simply update the logging level like this:
```python
import logging
logger = logging.getLogger("liesel")
logger.setLevel(logging.DEBUG)
```
Before, our setup required that you changed the level on the *handler*, which is less obvious:
```python
import logging
logger = logging.getLogger("liesel")
logger.handlers[0].setLevel(logging.DEBUG)
```

Update logging setup

---

CHANGELOG.md
liesel/model/model.py

The adoption of #92 caused warnings to be logged by default during model initialization, because the special nodes for the log likelihood and log probability cannot always be updated directly on their initialization. This PR just sets `update_on_init=False` for these nodes, which solves the issue.

Turn off update_on_init for special model nodes

---

setup.cfg

Cannot reproduce the issue reported in #185, so this PR simply removes the pin to scipy<=1.12.
Closes #185 
Opened as a draft to see if our CI passes.

Unpin scipy

---

.gitignore
docs/source/model.rst
docs/source/tutorials/md/01-lin-reg.md
docs/source/tutorials/md/07-groups.md
docs/source/tutorials/qmd/01-lin-reg.qmd
docs/source/tutorials/qmd/07-groups.qmd
liesel/model/__init__.py
liesel/model/goose.py
liesel/model/model.py
liesel/model/nodes.py
tests/model/test_goose.py
tests/model/test_graph_builder.py
tests/model/test_group.py
tests/model/test_legacy.py
tests/model/test_model.py
tests/model/test_node.py
tests/model/test_var.py

This PR goes back to a suggestion made by @Seb-Lorek :
>I find the naming of the node "Data" a bit unfortunate. I would have thought of Fixed or something like that. When you think of Data, you generally think of oberved data in the model. Also the description: "A Node subclass that holds constant data.". Doesn't help, it reminded me more of observed data. (Thought the description somehow fit: "Constant values better.")
I am not sure whether I am entirely happy with `Const`, because this class is also used as the `lsl.Var.value_node` of strong variables. If they are parameters, the values are not actually constant, but updated during sampling. So maybe `Value` would be better than `Const`. What do you guys think @GianmarcoCallegher @wiep? Of course this PR is not super urgent, so no need …

Rename Data -> Value; keep old name as an alias

---

liesel/model/model.py

There were some places in the GraphBuilder that had a hard-coded conversion to float32. I added an init argument that now makes it possible to avoid this behavior completely. The `lsl.Model` likewise gains the `to_float32` boolean flag as an argument, since if `grow=True`, the model internally uses a graph builder instance for growing.

Avoid hardcoded conversion to float32 in GraphBuilder

---

liesel/model/viz.py

As the title says. This reduces confusion about why plotted graphs may look chaotic.

Warn about missing PyGraphviz installation when plotting a lsl.Model

---

liesel/goose/builder.py
liesel/goose/engine.py

Currently, we use `tqdm(disable=None, ...)` for the sampling progress bar:
> It disables the progress bar in non-TTY environments. A TTY (teletypewriter) refers to environments like a terminal or console that supports interactive input/output. In non-TTY environments (e.g., file redirection or certain automated scripts), the progress bar is disabled.
Unfortunately, this has the effect of disabling the progress bar in Jupyter notebooks. This PR removes this argument.
If progress bar printing should be disabled, for example because you are running code on a server and logging output to a file, users can use the existing setting `EngineBuilder.show_progress = False`.
This notebook can be used to see the effect:
[test_sampling.ipynb.zip](https://github.com/user-attachments/files/16787026/test_ …

Enable progress bar in Jupyter notebooks

---

CHANGELOG.md
docs/source/tutorials/qmd/01a-transform.qmd
docs/source/tutorials/qmd/04-mcycle.qmd
liesel/model/model.py
liesel/model/nodes.py
tests/model/test_graph_builder.py
tests/model/test_model.py
tests/model/test_var.py

This PR introduces a `Var.transform` method. Some notes:
We currently have `GraphBuilder.transform`. The new method is in fact intended as a replacement for `GraphBuilder.transform`. Having `Var.transform` as a method on `Var` has the advantage that it is easier to find for users. Since the transformation is "doing something to a Var" and it does not actually require any functionality within the GraphBuilder, living as a method on a Var is a natural development for the transform method.
The method behaves similar to `GraphBuilder.transform`, with a few notable differences:
1. It will *not* use the default event space bijector from tensorflow by default. This change is made to encourage users to either select their desired bijector manually, which is often sensible, or to request an …

Make transform a method

---

conftest.py
docs/source/model.rst
docs/source/welcome.md
liesel/goose/optim.py
liesel/model/legacy.py
liesel/model/model.py
liesel/model/nodes.py
tests/model/test_var.py

For a while now, I have been a little unsatisfied with two things:
1. Incsonsistent UI: `Var` class vs. `param` and `obs` functions. See also #130 
2. The status of the `Data` (or, in #170 : `Value`) node vs. `Var`: Which should you use?
I think there is a satisfying solution:
1. Implement constructors for `Var` that fullfill the tasks above. 
2. Guide users to towards using `Var.new_<constructor>` as a default.
If I recall correctly, using constructors has been proposed before by @wiep.
This PR implements four constructors. 
Supersedes `lsl.param()`
```python
class Var:
@classmethod
def new_param(
cls, value: Any, distribution: Dist | None = None, name: str = ""
) -> Self:
...
```
Supersedes `lsl.obs()`
```python
class Var:
@classmethod
def new_obs(
cls, value: Any, distribution: Dist | …
```

Var constructors: new_param, new_obs, new_calc, new_value

---

liesel/model/model.py
tests/model/test_custom_log_prob.py

The use of transient nodes internally created by the GraphBuilder raised issues when later querying the log_prob using the `LieselInterface` as the `TransientNode`s do not have a valid model state. This fixes the issue by using `Calc` nodes instead.
Also, introduced tests. However, the tests for log_prior and log_lik use the internal node names.

Fixes issue with custom log prob in liesel models

---

liesel/model/viz.py

Fixes #217.
Adds an edge if input is used in value of a node that has also a distribution. Introduces a red edge if input is used in value and dist node.
Changes the created by the code
```py
import liesel.model as lsl
import jax.numpy as jnp
import tensorflow_probability.substrates.jax.distributions as tfd
x = lsl.Var(jnp.arange(4).astype(float), name="x")
y = lsl.Var(jnp.arange(4).astype(float), name="y")
batch_index = lsl.Var(
jnp.array([0, 1]),
name="batch_index",
)
y_sel_dist = lsl.Dist(lambda x, idx: tfd.Normal(x[idx], 1.0), x, batch_index)
y_sel_val = lsl.Calc(lambda y, idx: y[idx], y, batch_index)
y_sel_val.value
y_sel = lsl.Var(
y_sel_val,
y_sel_dist,
"y_sel",
)
model = lsl.GraphBuilder().add(y_sel_dist).build_model()
lsl.plot_vars(model)
```
from
to

Adds edge to plot_vars if input is used in value while var has distribution

---

liesel/model/nodes.py
tests/model/test_var.py

So far, we did not allow transformation of weak vars in `Var.transform`. I have a usecase for that right now, and I don't think anything really speaks against allowing it. This PR makes two small changes that enable the functionality.
If you transform a weak var, it gets inserted in between the old value node and the transformed variable:
```python
import liesel.model as lsl
import jax.numpy as jnp
import tensorflow_probability.substrates.jax.bijectors as tfb
tau = lsl.Var.new_param(10.0, name="tau")
tau_sqrt = lsl.Var.new_calc(jnp.sqrt, tau, name="tau_sqrt")
log_tau_sqrt = tau_sqrt.transform(tfb.Exp())
model = lsl.Model([tau_sqrt])
lsl.plot_vars(model)
```

Allow transformation of weak vars

---

liesel/goose/optim.py
setup.cfg

The issue in our code originated in the `liesel.goose.optim` module, specifically in the callback that updates the progress bar.
In the callback, the current loss values were accessed like this:
```python
i = val["while_i"]
loss_train = val["history"]["loss_train"][i]
loss_validation = val["history"]["loss_validation"][i]
```
Some experimentation revealed that this pattern was the problem. Introducing dedicated `"current_loss_train"` and `"current_loss_validation"` carry values solved the issue:
```python
loss_train = val["current_loss_train"]
loss_validation = val["current_loss_validation"]
```
While I was at it, I fixed two other issues with the progress bar:
1. There was a bug that prevented the argument `progress_bar=False` from taking effect, i.e. the progress bar couldn't be turned …

Weaken jax version pin to <0.5.0, closes #214

---

liesel/model/model.py
liesel/model/nodes.py
liesel/model/viz.py

All of the below applies to `plot_vars` as well as `plot_nodes`.
This PR adds methods to the `lsl.Var` and the `lsl.Model` objects that wrap the referenced plotting functions. The method on `lsl.Model` is inspired by the corresponding `lsl.GraphBuilder.plot_vars` method, which has existed for a long time and I find quite convenient.
The `lsl.Var.plot_vars` brings more novelty, because it is a way to very quickly plot intermediate sub-models. One tricky bit was to deal with the automatic naming: As soon as you initialize a model, Liesel will automatically assign names to unnamed nodes. Because `lsl.plot_vars` works similar to `lsl.GraphBuilder.plot_vars`, this also happens here: A helper model is built, then the plot is created, then the helper model is discarded. The issue is: The …

Implement Var.plot_vars and Model.plot_vars

---

liesel/model/nodes.py
tests/model/test_var.py

Small PR that allows users to specify a distribution in `Var.new_calc`. I originally thought this was unnecessary, but there are some edge cases when it might be useful. 
For example, in a copula model, you might have two strong variables with distributions representing the margins, and a weak calculator variable on the u-level after probability transformation. This weak caculator may receive the copula distribution to complete the setup.

Allow distributions in Var.new_calc

---

liesel/goose/summary_viz.py

The PR does what it says. In addition to
```python
results = engine.get_results()
samples = results.get_posterior_samples()
gs.plot_trace(results)
```
it is now possible to do 
```python
gs.plot_trace(samples)
```
for all plotting functions.
This is really useful in combination with predictions (#246), because you can look at diagnostic plots for computed quantities without having to include them in `eb.positions_included` during sampling, i.e. without having to have them baked into the `gs.SamplingResults` object.

Allow samples dictionary in plotting functions

---

tests/model/test_var.py

Closes #234 
Turns out, `dill` works also without modifying the `tfb.Invert` class. This PR now simply includes a test that confirms the behavior.
It also includes a commit with a small refactoring of the tests in `test_var.py` (using the standard imports instead of custom ones).

Test pickling model

---

liesel/goose/__init__.py
liesel/goose/summary_m.py
tests/goose/test_summary_m.py

This is a convenience summary class that takes a dictionary of samples/predictions as input. It plays very nicely with predictions as proposed in #246 and could also be used to create more targeted summaries for individual parameters.
Pseudocode illustration:
```python
samples = results.get_posterior_samples()
predictions = model.predict(samples)
summary_predictions = SamplesSummary(predictions)
summary_loc = SamplesSummary.from_array(predictions["loc"])
```
The `SamplesSummary` class basically replicates the `Summary.to_dataframe()` method. The way it is implemented in this PR is more of a quick implementation, and it contains large parts of copy-pasted code that was only slightly adapted. It is not very clean. But the whole `Summary` class code is not very clean and could really benefit …

Add SamplesSummary

---

liesel/goose/interface.py
liesel/model/model.py
liesel/model/nodes.py
tests/model/test_model.py
tests/model/test_var.py

This PR adds predictions to Liesel. The predictions are based on updating the model graph with new values repeatedly based on a dictionary of samples. For this, I use `jax.vmap`.
In the process, I added the methods `Model.extract_position()` and `Model.update_state()`, which basically mirror the corresponding methods in the `gs.LieselInterface`.
- Users can supply a dictionary of `newdata` at which to evaluate predictions. If they don't, `predict` uses the current values.
- Users can choose to evaluate predictions only for a subset of variables, indicated by a list of variable names. In this case, a `Model.parental_submodel()` for the selected variables is created. This avoids unnecessary computations and makes it possible to, for example in a regression setting, evaluate predictions on …

Add Model.predict and Var.predict

---

liesel/model/nodes.py
tests/model/test_var.py

With this PR, users can supply a `name` argument to `Var.transform()` in order to provide a custom name to their transformed variable.

Add 'name' argument to Var.transform

---

liesel/model/model.py
tests/model/test_model.py

This PR adds two small convenience properties to the `lsl.Model` class for direct access to parameter and observed variables.

Add Model.parameters and Model.observed properties

---

src/liesel/goose/engine.py

Jax supports donation of arguments to avoid memory reallocation. This PR enables the use in the engine. There shouldn't be a large speed improvements when the states are small and the number of iterations glued into one compiled call is large (like the default). Nonetheless, a small improvement.

Donate model state and kernel states in engine

---

docs/source/tutorials/qmd/03-gev.qmd
docs/source/tutorials/qmd/04-mcycle.qmd
src/liesel/model/distreg.py
src/liesel/model/nodes.py

Fixes the tutorials which are not working after inclusion of MCMCSpec in distreg builder and RLiesel.
closes #283.
✅ [tutorial workflow](https://github.com/liesel-devs/liesel/actions/runs/15043439181)

fixes tutorials

---

pyproject.toml
uv.lock

This PR removes the need to set the version number in two place (`pyproject.toml` and `__version__.py`). Now, only the latter is needed.

One place of truth for version number
