liesel-devs/liesel

.gitignore
liesel/goose/__init__.py
liesel/goose/summary_viz.py
tests/goose/test_summary_viz.py

Add the functions `gs.plot_scatter` and `gs.plot_pairs`.
Note that I also changed how parameter indices are displayed in plot labels. They are displayed now using square brackets instead of underscores. I think this provides a clearer distinction between the parameter name, which may contain underscores, and the index used to access a specific subparameter.
Before: beta_0
After: beta[0]
You can use this notebook for checking out the new functionality: [202207150909-pairplot.ipynb.zip](https://github.com/liesel-devs/liesel/files/9118973/202207150909-pairplot.ipynb.zip)

Feature: pair plots

---

liesel/goose/__init__.py
liesel/goose/mh.py
liesel/goose/mh_kernel.py
tests/goose/kernels/model_lm.py
tests/goose/kernels/test_mh_kernel.py

implements MH kernel with user-defined proposal function

Implements metropolis hastings kernel

---

setup.cfg

Closes https://github.com/liesel-devs/liesel-internal/issues/154

Bump jax and jaxlib versions

---

liesel/experimental/pymc.py
liesel/goose/summary_m.py
setup.cfg
tests/goose/test_summary_object.py

In this PR, I moved the functionality of the constructor `Summary.from_results` to the init and updated the class docstring accordingly. I also added the deprecation decorator to `Summary.from_results` and `Summary.from_result`.

Refactor gs.Summary

---

setup.cfg

Remove pdoc dependency

---

docs/source/conf.py

Allow docs to be built locally

---

.github/workflows/pytest.yml

This mini-PR fixes the issue that the code in `tests/` was included in the calculation of the test coverage. See, for example, this [run](https://github.com/liesel-devs/liesel/actions/runs/4253247018/jobs/7397852502). Here's the coverage report. Sorry for the extra lines for the line numbers, it's a copy-paste issue.
```
---------- coverage: platform linux, python 3.10.10-final-0 ----------
56
Name                                          Stmts   Miss  Cover
57
-----------------------------------------------------------------
58
conftest.py                                      34      4    88%
59
liesel/__init__.py                                4      0   100%
60
liesel/__version__.py                             2      0   100%
61
liesel/bijectors/__init__.py                      1 …
```

Fix test coverage calculation

---

docs/source/_templates/autosummary/class-without-inheritance-strict.rst
liesel/distributions/mvn_degen.py

A screenshot of the changed docs from local.
I also added public versions of the `._loc` and `._prec` attributes for completeness.

Improve mvn docs

---

liesel/model/goose.py
tests/model/test_goose.py

Create general discrete gibbs kernel hannes

---

CHANGELOG.md
liesel/goose/summary_m.py

Just a tiny PR for a small, but nice change.

Make error_df public (closes #94)

---

docs/source/tutorials/qmd/07-groups.qmd

There was a subtle coding error that led to unexpected behavior. See #131 . Now it's fixed.

Fix group tutorial (closes #131)

---

.pre-commit-config.yaml
tests/goose/deterministic_kernels.py
tests/model/test_var.py

update hooks' revisions in .pre-commit-config

---

.github/workflows/docs.yml
liesel/model/model.py
liesel/model/nodes.py

Updated documentation:
- lsl.Var
- lsl.Dist
- lsl.Calc
- lsl.Data
- lsl.Node
- lsl.param
- lsl.obs
- lsl.GraphBuilder
- lsl.Model
I didn't update the docs of the Transient... classes, because 1) I don't really know much about them and 2) I think for Liesel users, they are less important than the other nodes.

Improve node documentation

---

liesel/goose/builder.py
liesel/goose/interface.py

Addresses
- #118
- #113
For review, I am afraid the docs should be built and inspected locally.

Improve goose docs

---

docs/source/tutorials/qmd/01-lin-reg.qmd
docs/source/tutorials/qmd/01a-transform.qmd
docs/source/tutorials/qmd/02-ls-reg.qmd
docs/source/tutorials/qmd/tutorials.Rproj

The tutorials were quite outdated. I updated them to use the current API, fixed some issues, and simplified some code in the process.

Update linreg and distreg tutorials

---

docs/source/goose.rst
liesel/goose/builder.py
liesel/goose/engine.py
liesel/goose/epoch.py
liesel/goose/hmc.py
liesel/goose/interface.py
liesel/goose/iwls.py
liesel/goose/kernel_sequence.py
liesel/goose/nuts.py
liesel/goose/rw.py
liesel/goose/summary_m.py
liesel/model/distreg.py
liesel/model/goose.py
liesel/model/viz.py
setup.cfg
tests/distributions/test_mvn_degen.py

This PR includes updates to sphinx, sphinx-book-theme, and myst-nb. Now we are ready to use sphinx 7 🎉 ! Sphinx threw a lot of new warnings for ambiguous cross-references, which I also fixed in this PR. This PR adresses https://github.com/liesel-devs/liesel-internal/issues/187
After the update, Sphinx throws no more warnings except for two that I think are spurious. I documented them here:
- #178

Sphinx update

---

.pre-commit-config.yaml
docs/source/goose.rst
liesel/goose/__init__.py
liesel/goose/optim.py
setup.cfg
tests/goose/test_optim.py

This PR introduces the function `gs.optim`.
This function provides a quick-and-easy way to apply stochastic gradient descent to a `lsl.Model` - which can be nice for providing a "warm start" for MCMC sampling. All loops and batching are implemented in JAX.
Optimization can be applied on the whole dataset or in batches. By default, the Adam optimizer is used with a fixed learning rate of `0.1`. Users can supply an optimizer of their choice from the `optax` library.
The PR includes documentation and unit tests.
Here's a notebook for playing around:
[051-optim.ipynb.zip](https://github.com/liesel-devs/liesel/files/13780492/051-optim.ipynb.zip)

A function for applying stochastic gradient descent to a Liesel model

---

docs/source/conf.py

Closes #195 
This is a minimal change, basically implementing the solution recommended by readthedocs. @GianmarcoCallegher would you do the review?

Update docs base URL handling

---

.github/README.md
.github/README.qmd
docs/source/tutorials/md/01-lin-reg.md
docs/source/tutorials/qmd/01-lin-reg.qmd

This PR contains
1. An update to the linear regression tutorial, using the new `lsl.Var.new_param` etc. constructors, and using `gs.LieselInterface` for the Gibbs kernel.
2. An update to the project readme on GitHub, using the new `lsl.Var.new_param` etc. constructors.

Update linear regression tutorial and readme

---

.github/README.md
.github/README.qmd
.github/workflows/doctest.yml
.github/workflows/pre-commit.yml
.github/workflows/pytest-pull.yml
.github/workflows/pytest.yml
.github/workflows/tutorials.yml
.pre-commit-config.yaml
.readthedocs.yaml
liesel.Rproj
liesel/goose/summary_viz.py
pyproject.toml
setup.cfg
tests/conftest.py
tests/goose/test_builder.py

Unpin numpy, test against multiple python versions in CI

---

liesel/model/model.py
liesel/model/nodes.py
tests/model/test_node.py

As the title says. Closes https://github.com/liesel-devs/liesel-internal/issues/310

rename Calc(update_on_init) -> Calc(_update_on_init)

---

docs/source/index.rst

Add note on effort-based versioning to docs

---

src/liesel/goose/summary_viz.py

Add show arg to plot functions
